### ISSUE TITLE
Improve command line output

### ISSUE THREAD

**Issue by rnestler** [rnestler/rust-torrent-search#17]
Currently the command line output just uses the derived `Debug` trait implementation to print the torrents. A nicely formatted output would be appreciated.
Maybe look at [term](https://github.com/Stebalien/term) or [rust-ansi-term](https://github.com/ogham/rust-ansi-term). The later seems better documented.
 - [x] Add a term crate to Cargo.toml
 - [x] Add a function that formats a single torrent in color to src/torrent/mod.rs
 - [x] Use this function to print the output in src/main.rs

**Comment by rnestler** [comment]
@ubruhin @Luz Maybe one of you want's to try that one?

**Comment by jerzybrzoska** [comment]
Although it does not seem like this in the terminal window, the output is always a one very long line.  One can run this script to find this out:
```
#!/usr/bin/bash


searches=$(~/.cargo/bin/torrent-search --sort=seeders "${@}")

echo ${searches}>searches.txt
```
Changing the output of `torrent-search` so that at least each `S:[0-9]*/L:[0-9]*` begins with a new line would make it easier for me and other people to parse the output of `torrent-search`. This in turn should make this project more popular. As my knowledge of Rust is very elementary
I have no clue how big of a task it would be. But for sure such formatted output would be appreciated.

**Comment by rnestler** [comment]
> Although it does not seem like this in the terminal window, the output is always a one very long line.

This shouldn't be the case.

>     echo ${searches}>searches.txt

With this you remove the newlines. You'll need to quote the variables like this:
```
echo "${searches}" > searches.txt
```

See also https://unix.stackexchange.com/a/248228.
